[package]
name = "elias-text-editor"
authors = ["Elias Watson"]
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ete"
path = "src/main.rs"

[dependencies]
clap = { version = "4.0.29", features = ["derive"] }
crossterm = { version = "0.25.0", features = ["event-stream"] }
